######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 12 01:41:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h gotocelldialog.h sortdialog.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += finddialog.cpp gotocelldialog.cpp main.cpp sortdialog.cpp
