######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 15 20:47:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp
RESOURCES += Plotter.qrc
