######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 12 22:58:31 2014
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS       = \
                Qt4StartUp \
                CreateDialog \
                Spreadsheet \
                Plotter \

