######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 12 22:45:19 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cell.h \
           finddialog.h \
           gotocelldialog.h \
           mainwindow.h \
           sortdialog.h \
           spreadsheet.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += cell.cpp \
           finddialog.cpp \
           gotocelldialog.cpp \
           main.cpp \
           mainwindow.cpp \
           sortdialog.cpp \
           spreadsheet.cpp
RESOURCES += spreadsheet.qrc
