######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 12 01:39:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
